// Auth
export const AUTH_START = 'AUTH_START';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const CLEAR_SIGNUP = 'CLEAR_SIGNUP';
export const AUTH_CODE_SUCCESS = 'AUTH_CODE_SUCCESS';
export const AUTH_GUEST_SUCCESS = 'AUTH_GUEST_SUCCESS';
export const AUTH_ADMIN_SUCCESS = 'AUTH_ADMIN_SUCCESS';
export const AUTH_VERIFY_SUCCESS = 'AUTH_VERIFY_SUCCESS';
export const RESEND_CODE_SUCCESS = 'RESEND_CODE_SUCCESS';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_MESSAGE = 'AUTH_MESSAGE';
export const SAVE_USER = 'SAVE_USER';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SET_HASH = 'SET_HASH';



// Payment
export const GET_PLANS_START = 'GET_PLANS_START';
export const GET_PLANS_SUCCESS = 'GET_PLANS_SUCCESS';
export const GET_PLANS_FAIL = 'GET_PLANS_FAIL';
export const GET_PAYMENT_INFO_START = 'GET_PAYMENT_INFO_START';
export const GET_PAYMENT_INFO_SUCCESS = 'GET_PAYMENT_INFO_SUCCESS';
export const GET_PAYMENT_INFO_FAIL = 'GET_PAYMENT_INFO_FAIL';
export const POST_LIMO_PAYMENT_START = 'POST_LIMO_PAYMENT_START';
export const POST_LIMO_PAYMENT_SUCCESS = 'POST_LIMO_PAYMENT_SUCCESS';
export const POST_LIMO_PAYMENT_FAIL = 'POST_LIMO_PAYMENT_FAIL';



// Calculation
export const SET_SELECTED_PLAN = 'SET_SELECTED_PLAN';
export const GET_CALCULATE_START = 'GET_CALCULATE_START';
export const GET_CALCULATE_SUCCESS = 'GET_CALCULATE_SUCCESS';
export const GET_CALCULATE_FAIL = 'GET_CALCULATE_FAIL';
export const GET_USER_PLANS_START = 'GET_USER_PLANS_START';
export const GET_USER_PLANS_SUCCESS = 'GET_USER_PLANS_SUCCESS';
export const GET_USER_PLANS_FAIL = 'GET_USER_PLANS_FAIL';
export const MAKE_CALCULATION_START = 'MAKE_CALCULATION_START';
export const MAKE_CALCULATION_SUCCESS = 'MAKE_CALCULATION_SUCCESS';
export const MAKE_CALCULATION_FAIL = 'MAKE_CALCULATION_FAIL';



// Backend
export const RESET_USER_DASHBOARD = 'RESET_USER_DASHBOARD';
export const GET_USER_DASHBOARD_START = 'GET_USER_DASHBOARD_START';
export const GET_USER_DASHBOARD_SUCCESS = 'GET_USER_DASHBOARD_SUCCESS';
export const GET_USER_DASHBOARD_FAIL = 'GET_USER_DASHBOARD_FAIL';

export const RESET_USER_PACKAGES = 'RESET_USER_PACKAGES';
export const GET_USER_PACKAGES_START = 'GET_USER_PACKAGES_START';
export const GET_USER_PACKAGES_SUCCESS = 'GET_USER_PACKAGES_SUCCESS';
export const GET_USER_PACKAGES_FAIL = 'GET_USER_PACKAGES_FAIL';

export const RESET_USER_CALCULATE = 'RESET_USER_CALCULATE';
export const GET_USER_CALCULATE_PLANS_START = 'GET_USER_CALCULATE_PLANS_START';
export const GET_USER_CALCULATE_PLANS_SUCCESS = 'GET_USER_CALCULATE_PLANS_SUCCESS';
export const GET_USER_CALCULATE_PLANS_FAIL = 'GET_USER_CALCULATE_PLANS_FAIL';
export const GET_USER_CALCULATE_PLAN_START = 'GET_USER_CALCULATE_PLAN_START';
export const GET_USER_CALCULATE_PLAN_SUCCESS = 'GET_USER_CALCULATE_PLAN_SUCCESS';
export const GET_USER_CALCULATE_PLAN_FAIL = 'GET_USER_CALCULATE_PLAN_FAIL';
export const POST_USER_CALCULATE_START = 'POST_USER_CALCULATE_START';
export const POST_USER_CALCULATE_SUCCESS = 'POST_USER_CALCULATE_SUCCESS';
export const POST_USER_CALCULATE_FAIL = 'POST_USER_CALCULATE_FAIL';
export const RESET_SIMULATION = 'RESET_SIMULATION';

export const RESET_USER_NOTIFICATIONS = 'RESET_USER_NOTIFICATIONS';
export const GET_USER_NOTIFICATIONS_START = 'GET_USER_NOTIFICATIONS_START';
export const GET_USER_NOTIFICATIONS_SUCCESS = 'GET_USER_NOTIFICATIONS_SUCCESS';
export const GET_USER_NOTIFICATIONS_FAIL = 'GET_USER_NOTIFICATIONS_FAIL';
export const GET_USER_PAID_AMOUNT_START = 'GET_USER_PAID_AMOUNT_START';
export const GET_USER_PAID_AMOUNT_SUCCESS = 'GET_USER_PAID_AMOUNT_SUCCESS';
export const GET_USER_PAID_AMOUNT_FAIL = 'GET_USER_PAID_AMOUNT_FAIL';



export const RESET_ADMIN_DASHBOARD = 'RESET_ADMIN_DASHBOARD';
export const GET_ADMIN_DASHBOARD_START = 'GET_ADMIN_DASHBOARD_START';
export const GET_ADMIN_DASHBOARD_SUCCESS = 'GET_ADMIN_DASHBOARD_SUCCESS';
export const GET_ADMIN_DASHBOARD_FAIL = 'GET_ADMIN_DASHBOARD_FAIL';

export const RESET_ADMIN_USERS = 'RESET_ADMIN_USERS';
export const GET_ADMIN_USERS_START = 'GET_ADMIN_USERS_START';
export const GET_ADMIN_USERS_SUCCESS = 'GET_ADMIN_USERS_SUCCESS';
export const GET_ADMIN_USERS_FAIL = 'GET_ADMIN_USERS_FAIL';
export const POST_ADMIN_ADD_USER_START = 'POST_ADMIN_ADD_USER_START';
export const POST_ADMIN_ADD_USER_SUCCESS = 'POST_ADMIN_ADD_USER_SUCCESS';
export const POST_ADMIN_ADD_USER_FAIL = 'POST_ADMIN_ADD_USER_FAIL';

export const RESET_ADMIN_FINANCES = 'RESET_ADMIN_FINANCES';
export const GET_ADMIN_SALES_REPORT_START = 'GET_ADMIN_SALES_REPORT_START';
export const GET_ADMIN_SALES_REPORT_SUCCESS = 'GET_ADMIN_SALES_REPORT_SUCCESS';
export const GET_ADMIN_SALES_REPORT_FAIL = 'GET_ADMIN_SALES_REPORT_FAIL';
export const GET_ADMIN_LIMO_PAYMENTS_START = 'GET_ADMIN_LIMO_PAYMENTS_START';
export const GET_ADMIN_LIMO_PAYMENTS_SUCCESS = 'GET_ADMIN_LIMO_PAYMENTS_SUCCESS';
export const GET_ADMIN_LIMO_PAYMENTS_FAIL = 'GET_ADMIN_LIMO_PAYMENTS_FAIL';
export const GET_ADMIN_LIMO_PAYMENT_START = 'GET_ADMIN_LIMO_PAYMENT_START';
export const GET_ADMIN_LIMO_PAYMENT_SUCCESS = 'GET_ADMIN_LIMO_PAYMENT_SUCCESS';
export const GET_ADMIN_LIMO_PAYMENT_FAIL = 'GET_ADMIN_LIMO_PAYMENT_FAIL';
export const POST_ADMIN_LIMO_PAYMENT_START = 'POST_ADMIN_LIMO_PAYMENT_START';
export const POST_ADMIN_LIMO_PAYMENT_SUCCESS = 'POST_ADMIN_LIMO_PAYMENT_SUCCESS';
export const POST_ADMIN_LIMO_PAYMENT_FAIL = 'POST_ADMIN_LIMO_PAYMENT_FAIL';
export const GET_ADMIN_CREDITS_LIST_START = 'GET_ADMIN_CREDITS_LIST_START';
export const GET_ADMIN_CREDITS_LIST_SUCCESS = 'GET_ADMIN_CREDITS_LIST_SUCCESS';
export const GET_ADMIN_CREDITS_LIST_FAIL = 'GET_ADMIN_CREDITS_LIST_FAIL';
export const POST_ADMIN_ADD_CREDIT_START = 'POST_ADMIN_ADD_CREDIT_START';
export const POST_ADMIN_ADD_CREDIT_SUCCESS = 'POST_ADMIN_ADD_CREDIT_SUCCESS';
export const POST_ADMIN_ADD_CREDIT_FAIL = 'POST_ADMIN_ADD_CREDIT_FAIL';

export const RESET_ADMIN_PLANS = 'RESET_ADMIN_PLANS';
export const GET_ADMIN_PLANS_START = 'GET_ADMIN_PLANS_START';
export const GET_ADMIN_PLANS_SUCCESS = 'GET_ADMIN_PLANS_SUCCESS';
export const GET_ADMIN_PLANS_FAIL = 'GET_ADMIN_PLANS_FAIL';
export const POST_ADMIN_ADD_PLAN_START = 'POST_ADMIN_ADD_PLAN_START';
export const POST_ADMIN_ADD_PLAN_SUCCESS = 'POST_ADMIN_ADD_PLAN_SUCCESS';
export const POST_ADMIN_ADD_PLAN_FAIL = 'POST_ADMIN_ADD_PLAN_FAIL';
export const POST_ADMIN_PLAN_DEPOSIT_START = 'POST_ADMIN_PLAN_DEPOSIT_START';
export const POST_ADMIN_PLAN_DEPOSIT_SUCCESS = 'POST_ADMIN_PLAN_DEPOSIT_SUCCESS';
export const POST_ADMIN_PLAN_DEPOSIT_FAIL = 'POST_ADMIN_PLAN_DEPOSIT_FAIL';