// Auth
export const AUTH_START = 'AUTH_START';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const CLEAR_SIGNUP = 'CLEAR_SIGNUP';
export const AUTH_CODE_SUCCESS = 'AUTH_CODE_SUCCESS';
export const AUTH_GUEST_SUCCESS = 'AUTH_GUEST_SUCCESS';
export const AUTH_ADMIN_SUCCESS = 'AUTH_ADMIN_SUCCESS';
export const AUTH_VERIFY_SUCCESS = 'AUTH_VERIFY_SUCCESS';
export const RESEND_CODE_SUCCESS = 'RESEND_CODE_SUCCESS';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_MESSAGE = 'AUTH_MESSAGE';
export const SAVE_USER = 'SAVE_USER';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SET_HASH = 'SET_HASH';



// Payment
export const GET_PLANS_START = 'GET_PLANS_START';
export const GET_PLANS_SUCCESS = 'GET_PLANS_SUCCESS';
export const GET_PLANS_FAIL = 'GET_PLANS_FAIL';
export const GET_PAYMENT_INFO_START = 'GET_PAYMENT_INFO_START';
export const GET_PAYMENT_INFO_SUCCESS = 'GET_PAYMENT_INFO_SUCCESS';
export const GET_PAYMENT_INFO_FAIL = 'GET_PAYMENT_INFO_FAIL';
export const POST_LIMO_PAYMENT_START = 'POST_LIMO_PAYMENT_START';
export const POST_LIMO_PAYMENT_SUCCESS = 'POST_LIMO_PAYMENT_SUCCESS';
export const POST_LIMO_PAYMENT_FAIL = 'POST_LIMO_PAYMENT_FAIL';



// Calculation
export const SET_SELECTED_PLAN = 'SET_SELECTED_PLAN';
export const GET_CALCULATE_START = 'GET_CALCULATE_START';
export const GET_CALCULATE_SUCCESS = 'GET_CALCULATE_SUCCESS';
export const GET_CALCULATE_FAIL = 'GET_CALCULATE_FAIL';
export const GET_USER_PLANS_START = 'GET_USER_PLANS_START';
export const GET_USER_PLANS_SUCCESS = 'GET_USER_PLANS_SUCCESS';
export const GET_USER_PLANS_FAIL = 'GET_USER_PLANS_FAIL';
export const MAKE_CALCULATION_START = 'MAKE_CALCULATION_START';
export const MAKE_CALCULATION_SUCCESS = 'MAKE_CALCULATION_SUCCESS';
export const MAKE_CALCULATION_FAIL = 'MAKE_CALCULATION_FAIL';



// Backend
export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
export const NOTIFICATIONS_START = 'NOTIFICATIONS_START';
export const NOTIFICATIONS_SUCCESS = 'NOTIFICATIONS_SUCCESS';
export const NOTIFICATIONS_FAIL = 'NOTIFICATIONS_FAIL';

export const RESET_DASHBOARD = 'RESET_DASHBOARD';
export const DASHBOARD_START = 'DASHBOARD_START';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const DASHBOARD_FAIL = 'DASHBOARD_FAIL';

export const RESET_CONTACT_US = 'RESET_CONTACT_US';
export const CONTACT_US_START = 'CONTACT_US_START';
export const CONTACT_US_SUCCESS = 'CONTACT_US_SUCCESS';
export const CONTACT_US_FAIL = 'CONTACT_US_FAIL';

export const RESET_OPTIONS = 'RESET_OPTIONS';
export const OPTIONS_START = 'OPTIONS_START';
export const OPTIONS_SUCCESS = 'OPTIONS_SUCCESS';
export const OPTIONS_FAIL = 'OPTIONS_FAIL';



export const RESET_USER_PACKAGES = 'RESET_USER_PACKAGES';
export const GET_USER_PACKAGES_START = 'GET_USER_PACKAGES_START';
export const GET_USER_PACKAGES_SUCCESS = 'GET_USER_PACKAGES_SUCCESS';
export const GET_USER_PACKAGES_FAIL = 'GET_USER_PACKAGES_FAIL';

export const RESET_CALCULATE = 'RESET_CALCULATE';
export const CALCULATE_START = 'CALCULATE_START';
export const CALCULATE_SUCCESS = 'CALCULATE_SUCCESS';
export const CALCULATE_FAIL = 'CALCULATE_FAIL';
export const RESET_SIMULATION = 'RESET_SIMULATION';

export const GET_USER_PAID_AMOUNT_START = 'GET_USER_PAID_AMOUNT_START';
export const GET_USER_PAID_AMOUNT_SUCCESS = 'GET_USER_PAID_AMOUNT_SUCCESS';
export const GET_USER_PAID_AMOUNT_FAIL = 'GET_USER_PAID_AMOUNT_FAIL';




export const RESET_USERS = 'RESET_USERS';
export const USERS_START = 'USERS_START';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAIL = 'USERS_FAIL';

export const RESET_FINANCES = 'RESET_FINANCES';
export const FINANCES_START = 'FINANCES_START';
export const FINANCES_SUCCESS = 'FINANCES_SUCCESS';
export const FINANCES_FAIL = 'FINANCES_FAIL';

export const RESET_PLANS = 'RESET_PLANS';
export const PLANS_START = 'PLANS_START';
export const PLANS_SUCCESS = 'PLANS_SUCCESS';
export const PLANS_FAIL = 'PLANS_FAIL';