export const AUTH_START = 'AUTH_START';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_GUEST_SIGNUP_SUCCESS = 'AUTH_GUEST_SIGNUP_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SAVE_USER = 'SAVE_USER';
export const GET_TOKEN = 'GET_TOKEN';

export const GET_PLANS_START = 'GET_PLANS_START';
export const GET_PLANS_SUCCESS = 'GET_PLANS_SUCCESS';
export const GET_PLANS_FAIL = 'GET_PLANS_FAIL';
export const GET_PAYMENT_INFO_START = 'GET_PAYMENT_INFO_START';
export const GET_PAYMENT_INFO_SUCCESS = 'GET_PAYMENT_INFO_SUCCESS';
export const GET_PAYMENT_INFO_FAIL = 'GET_PAYMENT_INFO_FAIL';

export const GET_CALCULATE_START = 'GET_CALCULATE_START';
export const GET_CALCULATE_SUCCESS = 'GET_CALCULATE_SUCCESS';
export const GET_CALCULATE_FAIL = 'GET_CALCULATE_FAIL';
export const MAKE_CALCULATION_START = 'MAKE_CALCULATION_START';
export const MAKE_CALCULATION_SUCCESS = 'MAKE_CALCULATION_SUCCESS';
export const MAKE_CALCULATION_FAIL = 'MAKE_CALCULATION_FAIL';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
